<?php 
// FORMATO IMPRESORA
define("TIENDA_NOMBRE","SANTIAGO DE SURCO");
define("PIE_PAGINA","B633/A029/PO30128 /00000043/16:21");
//PARAMETROS IMPRESORA
define("TICKETERA_NOMBRE","ticketera");
define("TICKETERA_PC_NOMBRE","LAPTOP_WALT");
define("TICKETERA_PC_USUARIO","walther caceres:k1212");
 ?>